<ul class="nav navbar-nav navbar-right">
	<?php foreach ($this->container as $page) { ?>
		
		<?php $hasChildren = $page->hasPages(); ?>
		
	    <?php if( ! $hasChildren) { ?>
        <li><a href="<?php echo $page->getHref(); ?>"><?php echo $page->getLabel(); ?></a></li>
    	<?php } else { ?>
        <li class="dropdown">
            <a href="<?php echo $page->getHref(); ?>" class="dropdown-toggle" data-toggle="dropdown"><?php echo $page->getLabel(); ?> <b class="caret"></b></a>
            <ul class="dropdown-menu">
            <?php foreach($page->getPages() as $child) { ?>
            	<?php $subHasChildren = $child->hasPages(); ?>
            	<?php if( ! $subHasChildren) { ?>
                	<li><a href="<?php echo $child->getHref(); ?>"><?php echo $child->getLabel(); ?></a></li>
                <?php } else { ?>
                	<li class="dropdown">
                		<a href="<?php echo $child->getHref(); ?>" class="dropdown-toggle" data-toggle="dropdown"><?php echo $child->getLabel(); ?> <b class="caret"></b></a>
                	</li>
                <?php } ?>
            <?php } ?>
            </ul>
        </li>
        <?php } ?>
        
	<?php } ?>
</ul>